In [1]:
import pandas as pd

In [2]:
DIR = './data/dump.pkl'

In [4]:
pd.read_pickle(DIR)

{'stores':             id     store_name branch  area            tel  \
 0            1           Agal   None    홍대  010-6689-5886
 1            2         Assisy   None    광주   062-367-0700
 2            3  Battered Sole   None   이태원    02-749-6867
 3            4      Chakyoung   None  달맞이길   051-756-5566
 4            5       Delabobo   None   발산역   02-2667-9854
 ...        ...            ...    ...   ...            ...
 459983  459996         행복부대찌개   None   녹양동   031-877-2410
 459984  459997           행복부페   None   안중읍   031-682-1733
 459985  459998           행복분식   None   퇴촌면  031-8071-2668
 459986  459999           행복분식   None   소주동   055-312-3713
 459987  460000           행복분식   None  의정부동   031-772-6624

                       address   latitude   longitude   category
 0        서울특별시 마포구 동교동 170-13  37.556862  126.926666   아구찜|포장마차
 1         광주광역시 서구 농성동 631-33  35.150746  126.890062         카페
 2        서울특별시 용산구 이태원동 118-9  37.535032  126.991664    피쉬앤칩스|펍
 3       부산광역시 해운대구 중2동 1509-5  35.158587  129.175004  레스토랑|카프레제
 4           서울특별시 강서구 등촌동 689  37.559904  126.840512  디저트카페|디저트
 ...                       ...        ...         ...        ...
 459983     경기도 의정부시 녹양동 154-6  37.757939  127.032758
 459984  경기도 평택시 안중읍 용성리 718-3  37.002743  126.944991
 459985   경기도 광주 퇴촌면 도수리 611-6  37.471677  127.315744
 459986     경상남도 양산시 소주동 147-1  35.407860  129.158564
 459987    경기도 의정부시 의정부동 479-7  37.739845  127.038074

 [459988 rows x 9 columns],
 'reviews':          id   store    user  score  \
 0         1      15   68632      5
 1         2      18  389728      5
 2         3      19   68716      4
 3         4      37  774353      2
 4         5      38  115682      3
 ...     ...     ...     ...    ...
 91393  2401  360499   17371      5
 91394  2402  360505  198050      4
 91395  2403  360514  190766      5
 91396  2404  360514  201564      4
 91397  2405  360515  611078      5

                                                  content             reg_time
 0             전포 윗길에 새로 생긴! 호주에서 온 쉐프가 직접 요리하는 호주식 레스토랑!  1970-01-01 00:00:00
 1                        샌드위치 내용물도 알차게 들어있고 맛있었어요 가성비 추천  1970-01-01 00:00:00
 2      홈플러스 1층 매장 푸드코트 내 있는 매장인데 계란찜정식은 처음보고 시켜봣는데 사진...  1970-01-01 00:00:00
 3      전 여기 5년전에 가봤었는데 그때 기억은 별로였어요\n단체손님이 많았고, 차려지는건...  1970-01-01 00:00:00
 4      친구들끼리 술 간단하게마시러 감. 스끼다시 괜찮지만 회 양이 조금 부족한 느낌. 맛...  2019-03-15 22:16:47
 ...                                                  ...                  ...
 91393                                                     1970-01-01 00:00:00
 91394              닭발이 소스가 매운데 중독성있는 맛입니다. 마지막에 볶음밥 꼭드세요  1970-01-01 00:00:00
 91395                     늘 사람 많은 곳입니다. 소고기만 먹어도 배불러요! 굿  1970-01-01 00:00:00
 91396  고기가 엄청많이 먹고싶을 때 종종 들리는 곳이에요\n뷔페처럼 샐러드바에 사이드메뉴가...  1970-01-01 00:00:00
 91397                                                     1970-01-01 00:00:00

 [91398 rows x 6 columns],
 'menus':               id   store             menu_name    price
 0              1       3  메인 (피쉬앤칩스, 오리 가슴살 등)  14000.0
 1              2       3          스타터 보드(파테 등)  18000.0
 2              3       3        디저트 (초콜렛 퐁당 등)   8500.0
 3              4       3               생과일 칵테일   9000.0
 4              5       3                   생맥주   7000.0
 ...          ...     ...                   ...      ...
 1651852  1651853  456309           전복/해삼/소라(중)  50000.0
 1651853  1651854  456309           전복/해삼/소라(대)  70000.0
 1651854  1651855  456309                    문어      0.0
 1651855  1651856  456309                   돌멍게      0.0
 1651856  1651857  456309                 오늘의 회      0.0

 [1651857 rows x 4 columns],
 'users':            id gender  age
 0           7      남   49
 1          15      여   26
 2          23      남   43
 3          62      여   33
 4          64      남   33
 ...       ...    ...  ...
 18987  949946      여   47
 18988  949951      남   49
 18989  950224      남   49
 18990  950225      남   56
 18991  950331      남   49

 [18992 rows x 3 columns]}

In [5]:
print(pd.__version__)

1.3.2